Build Fix
There are build errors on IVI as follows, so GetWindowHandle member function
is added to convert gfx::AcceleratedWidget to unsigned type.

../../ozone/ui/desktop_aura/window_tree_host_delegate_wayland.cc:58:69: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (!current_active_window_ || current_active_window_->window_ != handle ||
                                                                     ^
../../ozone/ui/desktop_aura/window_tree_host_delegate_wayland.cc: In member function ‘void views::WindowTreeHostDelegateWayland::SetActiveWindow(views::DesktopWindowTreeHostWayland*)’:
../../ozone/ui/desktop_aura/window_tree_host_delegate_wayland.cc:87:26: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (windows.front() != window_handle) {
                          ^
../../ozone/ui/desktop_aura/window_tree_host_delegate_wayland.cc: In member function ‘virtual void views::WindowTreeHostDelegateWayland::OnWindowFocused(unsigned int)’:
../../ozone/ui/desktop_aura/window_tree_host_delegate_wayland.cc:223:50: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
           current_capture_->GetAcceleratedWidget() : true;
                                                  ^
../../ozone/ui/desktop_aura/window_tree_host_delegate_wayland.cc:224:42: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (current_active_window_->window_ == handle)
                                          ^
../../ozone/ui/desktop_aura/window_tree_host_delegate_wayland.cc: In member function ‘virtual void views::WindowTreeHostDelegateWayland::OnWindowClose(unsigned int)’:
../../ozone/ui/desktop_aura/window_tree_host_delegate_wayland.cc:257:36: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   if (current_capture_->window_ != handle)